extends:
  - ./eslint-internal/config/es2020.js
  - ./eslint-internal/config/+eslint-plugin.js

ignorePatterns:
  - /.nyc_output
  - /coverage
  - /node_modules
  - "*.ts"
  - "!.vuepress"
  - /docs/.vuepress/dist

overrides:
  - files: lib/rules/**/*.js
    rules:
      "eslint-plugin/require-meta-docs-url":
        - error
        - pattern: http://ota-meshi.github.io/eslint-plugin-es-x/rules/{{name}}.html
