extends:
  - ./eslint-internal/config/es2020.js
  - ./eslint-internal/config/+eslint-plugin.js

ignorePatterns:
  - /.nyc_output
  - /coverage
  - /node_modules
  - "*.ts"
  - "!.vuepress"
  - /docs/.vuepress/dist

globals:
  fetch: readonly

overrides:
  - files: lib/rules/**/*.js
    rules:
      "eslint-plugin/require-meta-docs-url":
        - error
        - pattern: http://eslint-community.github.io/eslint-plugin-es-x/rules/{{name}}.html
