/**
 * @author Toru Nagashima <https://github.com/mysticatea>
 * See LICENSE file in root directory for full license.
 */
import {
    CALL,
    CONSTRUCT,
    PatternMatcher,
    ReferenceTracker,
    getPropertyName,
    getStringIfConstant,
} from "@eslint-community/eslint-utils"
import type { AST, Scope, SourceCode } from "eslint"
import type {
    MethodDefinition,
    NewExpression,
    PropertyDefinition,
    SimpleCallExpression,
} from "estree"

/**
 * Define generator to search pattern.
 * The iterator generated by the generator returns the start and end index of the match.
 * @param pattern Base pattern
 * @returns generator
 */
export function definePatternSearchGenerator(
    pattern: RegExp,
): (str: string) => IterableIterator<RegExpExecArray> {
    const matcher = new PatternMatcher(pattern)
    return matcher.execAll.bind(matcher)
}

/**
 * Check whether a given token is a comma token or not.
 * @param token The token to check.
 * @returns `true` if the token is a comma token.
 */
export function isCommaToken(
    token: AST.Token | null | undefined,
): token is AST.Token & { type: "Punctuator"; value: "," } {
    return token != null && token.type === "Punctuator" && token.value === ","
}

/**
 * Iterate the calls of the `RegExp` global variable.
 * @param globalScope The global scope object.
 * @returns The iterator of `CallExpression` or `NewExpression` for `RegExp`.
 */
export function* getRegExpCalls(globalScope: Scope.Scope): IterableIterator<{
    node: NewExpression | SimpleCallExpression
    pattern: string | null
    flags: string | null
}> {
    const tracker = new ReferenceTracker(globalScope)
    for (const { node } of tracker.iterateGlobalReferences({
        RegExp: { [CALL]: true, [CONSTRUCT]: true },
    })) {
        const callNode = node as NewExpression | SimpleCallExpression
        const [patternNode, flagsNode] = callNode.arguments
        yield {
            node: callNode,
            pattern: getStringIfConstant(patternNode, globalScope),
            flags: getStringIfConstant(flagsNode, globalScope),
        }
    }
}

/**
 * Get the name of the given node.
 * @param node The node to get.
 * @param sourceCode The source code object to get the code of computed property keys.
 * @returns The name of the node.
 */
export function getFieldName(
    node: PropertyDefinition | MethodDefinition,
    sourceCode?: SourceCode | null,
): string {
    if (node.key.type === "PrivateIdentifier") {
        return `#${node.key.name}`
    }
    const name = getPropertyName(node)
    if (name) {
        return `'${name}'`
    }

    if (sourceCode) {
        const keyText = sourceCode.getText(node.key)
        if (!keyText.includes("\n")) {
            return `[${keyText}]`
        }
    }
    return ""
}
