/**
 * DON'T EDIT THIS FILE.
 * This file was generated by "scripts/update-lib-flat-configs.ts" script.
 */
import type { Linter } from "eslint"
import plugin from "../../index.ts"

const config: Linter.Config = {
    name: "es-x/no-arraybuffer-base64",
    plugins: {
        get "es-x"() {
            return plugin
        },
    },
    rules: {
        "es-x/no-uint8array-frombase64": "error",
        "es-x/no-uint8array-fromhex": "error",
        "es-x/no-uint8array-prototype-setfrombase64": "error",
        "es-x/no-uint8array-prototype-setfromhex": "error",
        "es-x/no-uint8array-prototype-tobase64": "error",
        "es-x/no-uint8array-prototype-tohex": "error",
    },
}

export default config
