/**
 * DON'T EDIT THIS FILE.
 * This file was generated by "scripts/update-lib-flat-configs.ts" script.
 */
import type { Linter } from "eslint"
import plugin from "../../index"

const config: Linter.Config = {
    name: "es-x/no-explicit-resource-management",
    plugins: {
        get "es-x"() {
            return plugin
        },
    },
    rules: {
        "es-x/no-asyncdisposablestack": "error",
        "es-x/no-disposablestack": "error",
        "es-x/no-suppressederror": "error",
        "es-x/no-symbol-asyncdispose": "error",
        "es-x/no-symbol-dispose": "error",
        "es-x/no-using-declarations": "error",
    },
}

export default config
