/**
 * DON'T EDIT THIS FILE.
 * This file was generated by "scripts/update-lib-flat-configs.ts" script.
 */
import type { Linter } from "eslint"
import plugin from "../../index.ts"

const config: Linter.Config = {
    name: "es-x/no-float16array",
    plugins: {
        get "es-x"() {
            return plugin
        },
    },
    rules: {
        "es-x/no-dataview-prototype-getfloat16-setfloat16": "error",
        "es-x/no-float16array": "error",
        "es-x/no-math-f16round": "error",
    },
}

export default config
