/**
 * DON'T EDIT THIS FILE.
 * This file was generated by "scripts/update-lib-flat-configs.ts" script.
 */
import type { Linter } from "eslint"
import plugin from "../../index.ts"

const config: Linter.Config = {
    name: "es-x/no-is-usv-string",
    plugins: {
        get "es-x"() {
            return plugin
        },
    },
    rules: {
        "es-x/no-string-prototype-iswellformed": "error",
        "es-x/no-string-prototype-towellformed": "error",
    },
}

export default config
