/**
 * DON'T EDIT THIS FILE.
 * This file was generated by "scripts/update-lib-flat-configs.ts" script.
 */
import type { Linter } from "eslint"
import plugin from "../../index.ts"

const config: Linter.Config = {
    name: "es-x/no-import-attributes",
    plugins: {
        get "es-x"() {
            return plugin
        },
    },
    rules: {
        "es-x/no-dynamic-import-options": "error",
        "es-x/no-import-attributes": "error",
        "es-x/no-trailing-dynamic-import-commas": "error",
    },
}

export default config
