/**
 * DON'T EDIT THIS FILE.
 * This file was generated by "scripts/update-lib-flat-configs.ts" script.
 */
import type { Linter } from "eslint"
import plugin from "../../index.ts"

const config: Linter.Config = {
    name: "es-x/no-intl-locale-info",
    plugins: {
        get "es-x"() {
            return plugin
        },
    },
    rules: {
        "es-x/no-intl-locale-prototype-firstdayofweek": "error",
        "es-x/no-intl-locale-prototype-getcalendars": "error",
        "es-x/no-intl-locale-prototype-getcollations": "error",
        "es-x/no-intl-locale-prototype-gethourcycles": "error",
        "es-x/no-intl-locale-prototype-getnumberingsystems": "error",
        "es-x/no-intl-locale-prototype-gettextinfo": "error",
        "es-x/no-intl-locale-prototype-gettimezones": "error",
        "es-x/no-intl-locale-prototype-getweekinfo": "error",
    },
}

export default config
