/**
 * DON'T EDIT THIS FILE.
 * This file was generated by "scripts/update-lib-flat-configs.ts" script.
 */
import type { Linter } from "eslint"
import plugin from "../../index.ts"

const config: Linter.Config = {
    name: "es-x/no-iterator-helpers",
    plugins: {
        get "es-x"() {
            return plugin
        },
    },
    rules: {
        "es-x/no-iterator-prototype-drop": "error",
        "es-x/no-iterator-prototype-every": "error",
        "es-x/no-iterator-prototype-filter": "error",
        "es-x/no-iterator-prototype-find": "error",
        "es-x/no-iterator-prototype-flatmap": "error",
        "es-x/no-iterator-prototype-foreach": "error",
        "es-x/no-iterator-prototype-map": "error",
        "es-x/no-iterator-prototype-reduce": "error",
        "es-x/no-iterator-prototype-some": "error",
        "es-x/no-iterator-prototype-take": "error",
        "es-x/no-iterator-prototype-toarray": "error",
        "es-x/no-iterator": "error",
    },
}

export default config
