/**
 * DON'T EDIT THIS FILE.
 * This file was generated by "scripts/update-lib-flat-configs.ts" script.
 */
import type { Linter } from "eslint"
import plugin from "../../index.ts"

const config: Linter.Config = {
    name: "es-x/no-json-parse-with-source",
    plugins: {
        get "es-x"() {
            return plugin
        },
    },
    rules: {
        "es-x/no-json-israwjson": "error",
        "es-x/no-json-parse-reviver-context-parameter": "error",
        "es-x/no-json-rawjson": "error",
    },
}

export default config
