/**
 * DON'T EDIT THIS FILE.
 * This file was generated by "scripts/update-lib-flat-configs.ts" script.
 */
import type { Linter } from "eslint"
import plugin from "../../index"

const config: Linter.Config = {
    name: "es-x/no-joint-iteration",
    plugins: {
        get "es-x"() {
            return plugin
        },
    },
    rules: {
        "es-x/no-iterator-zip": "error",
        "es-x/no-iterator-zipkeyed": "error",
    },
}

export default config
