/**
 * DON'T EDIT THIS FILE.
 * This file was generated by "scripts/update-lib-flat-configs.ts" script.
 */
import type { Linter } from "eslint"
import plugin from "../../index"

const config: Linter.Config = {
    name: "es-x/no-new-in-es2021",
    plugins: {
        get "es-x"() {
            return plugin
        },
    },
    rules: {
        "es-x/no-logical-assignment-operators": "error",
        "es-x/no-numeric-separators": "error",
        "es-x/no-promise-any": "error",
        "es-x/no-regexp-unicode-property-escapes-2021": "error",
        "es-x/no-string-prototype-replaceall": "error",
        "es-x/no-weakrefs": "error",
    },
}

export default config
