/**
 * DON'T EDIT THIS FILE.
 * This file was generated by "scripts/update-lib-flat-configs.ts" script.
 */
import type { Linter } from "eslint"
import plugin from "../../index.ts"

const config: Linter.Config = {
    name: "es-x/no-new-in-es2023",
    plugins: {
        get "es-x"() {
            return plugin
        },
    },
    rules: {
        "es-x/no-array-prototype-findlast-findlastindex": "error",
        "es-x/no-array-prototype-toreversed": "error",
        "es-x/no-array-prototype-tosorted": "error",
        "es-x/no-array-prototype-tospliced": "error",
        "es-x/no-array-prototype-with": "error",
        "es-x/no-hashbang": "error",
        "es-x/no-regexp-unicode-property-escapes-2023": "error",
    },
}

export default config
