/**
 * DON'T EDIT THIS FILE.
 * This file was generated by "scripts/update-lib-flat-configs.ts" script.
 */
import type { Linter } from "eslint"
import plugin from "../../index"

const config: Linter.Config = {
    name: "es-x/no-new-in-es2019",
    plugins: {
        get "es-x"() {
            return plugin
        },
    },
    rules: {
        "es-x/no-array-prototype-flat": "error",
        "es-x/no-json-superset": "error",
        "es-x/no-object-fromentries": "error",
        "es-x/no-optional-catch-binding": "error",
        "es-x/no-regexp-unicode-property-escapes-2019": "error",
        "es-x/no-string-prototype-trimstart-trimend": "error",
        "es-x/no-symbol-prototype-description": "error",
    },
}

export default config
