/**
 * DON'T EDIT THIS FILE.
 * This file was generated by "scripts/update-lib-flat-configs.ts" script.
 */
import type { Linter } from "eslint"
import plugin from "../../index"

const config: Linter.Config = {
    name: "es-x/no-new-in-es2024",
    plugins: {
        get "es-x"() {
            return plugin
        },
    },
    rules: {
        "es-x/no-arraybuffer-prototype-transfer": "error",
        "es-x/no-atomics-waitasync": "error",
        "es-x/no-map-groupby": "error",
        "es-x/no-object-groupby": "error",
        "es-x/no-promise-withresolvers": "error",
        "es-x/no-regexp-v-flag": "error",
        "es-x/no-resizable-and-growable-arraybuffers": "error",
        "es-x/no-string-prototype-iswellformed": "error",
        "es-x/no-string-prototype-towellformed": "error",
    },
}

export default config
