/**
 * DON'T EDIT THIS FILE.
 * This file was generated by "scripts/update-lib-flat-configs.ts" script.
 */
import type { Linter } from "eslint"
import plugin from "../../index"

const config: Linter.Config = {
    name: "es-x/no-new-in-es2022",
    plugins: {
        get "es-x"() {
            return plugin
        },
    },
    rules: {
        "es-x/no-arbitrary-module-namespace-names": "error",
        "es-x/no-array-prototype-at": "error",
        "es-x/no-class-instance-fields": "error",
        "es-x/no-class-private-fields": "error",
        "es-x/no-class-private-methods": "error",
        "es-x/no-class-static-block": "error",
        "es-x/no-class-static-fields": "error",
        "es-x/no-error-cause": "error",
        "es-x/no-object-hasown": "error",
        "es-x/no-private-in": "error",
        "es-x/no-regexp-d-flag": "error",
        "es-x/no-regexp-unicode-property-escapes-2022": "error",
        "es-x/no-string-prototype-at": "error",
        "es-x/no-top-level-await": "error",
    },
}

export default config
