/**
 * DON'T EDIT THIS FILE.
 * This file was generated by "scripts/update-lib-flat-configs.ts" script.
 */
import type { Linter } from "eslint"
import plugin from "../../index.ts"

const config: Linter.Config = {
    name: "es-x/no-new-in-es2017",
    plugins: {
        get "es-x"() {
            return plugin
        },
    },
    rules: {
        "es-x/no-async-functions": "error",
        "es-x/no-atomics": "error",
        "es-x/no-object-entries": "error",
        "es-x/no-object-getownpropertydescriptors": "error",
        "es-x/no-object-values": "error",
        "es-x/no-shared-array-buffer": "error",
        "es-x/no-string-prototype-padstart-padend": "error",
        "es-x/no-trailing-function-commas": "error",
    },
}

export default config
