/**
 * DON'T EDIT THIS FILE.
 * This file was generated by "scripts/update-lib-flat-configs.ts" script.
 */
import type { Linter } from "eslint"
import plugin from "../../index"

const config: Linter.Config = {
    name: "es-x/no-new-in-es2020",
    plugins: {
        get "es-x"() {
            return plugin
        },
    },
    rules: {
        "es-x/no-bigint": "error",
        "es-x/no-dynamic-import": "error",
        "es-x/no-export-ns-from": "error",
        "es-x/no-global-this": "error",
        "es-x/no-import-meta": "error",
        "es-x/no-nullish-coalescing-operators": "error",
        "es-x/no-optional-chaining": "error",
        "es-x/no-promise-all-settled": "error",
        "es-x/no-regexp-unicode-property-escapes-2020": "error",
        "es-x/no-string-prototype-matchall": "error",
        "es-x/no-symbol-matchall": "error",
    },
}

export default config
