/**
 * DON'T EDIT THIS FILE.
 * This file was generated by "scripts/update-lib-flat-configs.ts" script.
 */
import type { Linter } from "eslint"
import plugin from "../../index"

const config: Linter.Config = {
    name: "es-x/no-set-methods",
    plugins: {
        get "es-x"() {
            return plugin
        },
    },
    rules: {
        "es-x/no-set-prototype-difference": "error",
        "es-x/no-set-prototype-intersection": "error",
        "es-x/no-set-prototype-isdisjointfrom": "error",
        "es-x/no-set-prototype-issubsetof": "error",
        "es-x/no-set-prototype-issupersetof": "error",
        "es-x/no-set-prototype-symmetricdifference": "error",
        "es-x/no-set-prototype-union": "error",
    },
}

export default config
