/**
 * DON'T EDIT THIS FILE.
 * This file was generated by "scripts/update-lib-flat-configs.ts" script.
 */
import type { Linter } from "eslint"
import plugin from "../../index.ts"

const config: Linter.Config = {
    name: "es-x/no-upsert",
    plugins: {
        get "es-x"() {
            return plugin
        },
    },
    rules: {
        "es-x/no-map-prototype-getorinsert": "error",
        "es-x/no-map-prototype-getorinsertcomputed": "error",
        "es-x/no-weakmap-prototype-getorinsert": "error",
        "es-x/no-weakmap-prototype-getorinsertcomputed": "error",
    },
}

export default config
