/**
 * DON'T EDIT THIS FILE.
 * This file was generated by "scripts/update-lib-flat-configs.js" script.
 */
"use strict"

module.exports = {
    name: "es-x/no-upsert",
    plugins: {
        get "es-x"() {
            return require("../../index.js")
        },
    },
    rules: {
        "es-x/no-map-prototype-getorinsert": "error",
        "es-x/no-map-prototype-getorinsertcomputed": "error",
        "es-x/no-weakmap-prototype-getorinsert": "error",
        "es-x/no-weakmap-prototype-getorinsertcomputed": "error",
    },
}
