/**
 * DON'T EDIT THIS FILE.
 * This file was generated by "scripts/update-lib-flat-configs.ts" script.
 */
import type { Linter } from "eslint"
import plugin from "../../index"
import noNewInEs2026Config from "./no-new-in-es2026"
import noNewInEs2025Config from "./no-new-in-es2025"

const config: Linter.Config = {
    name: "es-x/restrict-to-es2024",
    plugins: {
        get "es-x"() {
            return plugin
        },
    },
    rules: { ...noNewInEs2026Config.rules, ...noNewInEs2025Config.rules },
}

export default config
