/**
 * DON'T EDIT THIS FILE.
 * This file was generated by "scripts/update-lib-flat-configs.ts" script.
 */
import type { Linter } from "eslint"
import plugin from "../../index"
import noNewInEs2026Config from "./no-new-in-es2026"
import noNewInEs2025Config from "./no-new-in-es2025"
import noNewInEs2024Config from "./no-new-in-es2024"
import noNewInEs2023Config from "./no-new-in-es2023"

const config: Linter.Config = {
    name: "es-x/restrict-to-es2022",
    plugins: {
        get "es-x"() {
            return plugin
        },
    },
    rules: {
        ...noNewInEs2026Config.rules,
        ...noNewInEs2025Config.rules,
        ...noNewInEs2024Config.rules,
        ...noNewInEs2023Config.rules,
    },
}

export default config
