/**
 * DON'T EDIT THIS FILE.
 * This file was generated by "scripts/update-lib-flat-configs.ts" script.
 */
import type { Linter } from "eslint"
import plugin from "../../index.ts"
import noNewInEs2026IntlApiConfig from "./no-new-in-es2026-intl-api.ts"
import noNewInEs2025IntlApiConfig from "./no-new-in-es2025-intl-api.ts"
import noNewInEs2024IntlApiConfig from "./no-new-in-es2024-intl-api.ts"
import noNewInEs2023IntlApiConfig from "./no-new-in-es2023-intl-api.ts"

const config: Linter.Config = {
    name: "es-x/restrict-to-es2022-intl-api",
    plugins: {
        get "es-x"() {
            return plugin
        },
    },
    rules: {
        ...noNewInEs2026IntlApiConfig.rules,
        ...noNewInEs2025IntlApiConfig.rules,
        ...noNewInEs2024IntlApiConfig.rules,
        ...noNewInEs2023IntlApiConfig.rules,
    },
}

export default config
