/**
 * DON'T EDIT THIS FILE.
 * This file was generated by "scripts/update-lib-flat-configs.ts" script.
 */
import type { Linter } from "eslint"
import plugin from "../../index.ts"
import noNewInEs2026Config from "./no-new-in-es2026.ts"
import noNewInEs2025Config from "./no-new-in-es2025.ts"
import noNewInEs2024Config from "./no-new-in-es2024.ts"
import noNewInEs2023Config from "./no-new-in-es2023.ts"
import noNewInEs2022Config from "./no-new-in-es2022.ts"
import noNewInEs2021Config from "./no-new-in-es2021.ts"
import noNewInEs2020Config from "./no-new-in-es2020.ts"

const config: Linter.Config = {
    name: "es-x/restrict-to-es2019",
    plugins: {
        get "es-x"() {
            return plugin
        },
    },
    rules: {
        ...noNewInEs2026Config.rules,
        ...noNewInEs2025Config.rules,
        ...noNewInEs2024Config.rules,
        ...noNewInEs2023Config.rules,
        ...noNewInEs2022Config.rules,
        ...noNewInEs2021Config.rules,
        ...noNewInEs2020Config.rules,
    },
}

export default config
