/**
 * DON'T EDIT THIS FILE.
 * This file was generated by "scripts/update-lib-flat-configs.ts" script.
 */
import type { Linter } from "eslint"
import plugin from "../../index"
import noNewInEs2026Config from "./no-new-in-es2026"
import noNewInEs2025Config from "./no-new-in-es2025"
import noNewInEs2024Config from "./no-new-in-es2024"
import noNewInEs2023Config from "./no-new-in-es2023"
import noNewInEs2022Config from "./no-new-in-es2022"
import noNewInEs2021Config from "./no-new-in-es2021"
import noNewInEs2020Config from "./no-new-in-es2020"
import noNewInEs2019Config from "./no-new-in-es2019"
import noNewInEs2018Config from "./no-new-in-es2018"
import noNewInEs2017Config from "./no-new-in-es2017"
import noNewInEs2016Config from "./no-new-in-es2016"
import noNewInEs2015Config from "./no-new-in-es2015"

const config: Linter.Config = {
    name: "es-x/restrict-to-es5",
    plugins: {
        get "es-x"() {
            return plugin
        },
    },
    rules: {
        ...noNewInEs2026Config.rules,
        ...noNewInEs2025Config.rules,
        ...noNewInEs2024Config.rules,
        ...noNewInEs2023Config.rules,
        ...noNewInEs2022Config.rules,
        ...noNewInEs2021Config.rules,
        ...noNewInEs2020Config.rules,
        ...noNewInEs2019Config.rules,
        ...noNewInEs2018Config.rules,
        ...noNewInEs2017Config.rules,
        ...noNewInEs2016Config.rules,
        ...noNewInEs2015Config.rules,
    },
}

export default config
