import { writeFile } from "node:fs/promises"
import * as path from "node:path"
import { setTimeout as sleep } from "node:timers/promises"
import { JSDOM, type DOMWindow } from "jsdom"
import { ESLint } from "eslint"
import { getLatestUnicodeGeneralCategoryValues } from "./get-latest-unicode-general-category-values"
import { getLatestUnicodeScriptValues } from "./get-latest-unicode-script-values"

const DATA_SOURCES = [
    {
        url: "https://262.ecma-international.org/9.0/",
        version: 2018,
        binProperties: "#table-binary-unicode-properties",
        gcValues: "#table-unicode-general-category-values",
        scValues: "#table-unicode-script-values",
    },
    {
        url: "https://262.ecma-international.org/10.0/",
        version: 2019,
        binProperties: "#table-binary-unicode-properties",
        gcValues: "#table-unicode-general-category-values",
        scValues: "#table-unicode-script-values",
    },
    {
        url: "https://262.ecma-international.org/11.0/",
        version: 2020,
        binProperties: "#table-binary-unicode-properties",
        gcValues: "#table-unicode-general-category-values",
        scValues: "#table-unicode-script-values",
    },
    {
        url: "https://262.ecma-international.org/12.0/",
        version: 2021,
        binProperties: "#table-binary-unicode-properties",
        gcValues: "#table-unicode-general-category-values",
        scValues: "#table-unicode-script-values",
    },
    {
        url: "https://tc39.es/ecma262/2022/multipage/text-processing.html",
        version: 2022,
        binProperties: "#table-binary-unicode-properties",
        gcValues: "#table-unicode-general-category-values",
        scValues: "#table-unicode-script-values",
    },
    {
        url: "https://tc39.es/ecma262/2023/multipage/text-processing.html",
        version: 2023,
        binProperties: "#table-binary-unicode-properties",
        gcValues: getLatestUnicodeGeneralCategoryValues,
        scValues: getLatestUnicodeScriptValues,
    },
    {
        url: "https://tc39.es/ecma262/2024/multipage/text-processing.html",
        version: 2024,
        binProperties: "#table-binary-unicode-properties",
        gcValues: getLatestUnicodeGeneralCategoryValues,
        scValues: getLatestUnicodeScriptValues,
    },
    {
        url: "https://tc39.es/ecma262/2025/multipage/text-processing.html",
        version: 2025,
        binProperties: "#table-binary-unicode-properties",
        gcValues: getLatestUnicodeGeneralCategoryValues,
        scValues: getLatestUnicodeScriptValues,
    },
    {
        url: "https://tc39.es/ecma262/multipage/text-processing.html",
        version: 2026,
        binProperties: "#table-binary-unicode-properties",
        gcValues: getLatestUnicodeGeneralCategoryValues,
        scValues: getLatestUnicodeScriptValues,
    },
]
const FILE_PATH = path.resolve(__dirname, "../lib/util/unicode-properties.ts")
const logger = console

// Main
;(async () => {
    const data = Object.create(null) as Record<
        number,
        {
            binProperties: string[]
            gcValues: string[]
            scValues: string[]
        }
    >
    const existing = {
        binProperties: new Set<string>(),
        gcValues: new Set<string>(),
        scValues: new Set<string>(),
    }

    for (const {
        binProperties,
        gcValues,
        scValues,
        url,
        version,
    } of DATA_SOURCES) {
        logger.log("---- ECMAScript %d ----", version)
        const datum = {
            binProperties: [] as string[],
            gcValues: [] as string[],
            scValues: [] as string[],
        }
        data[version] = datum

        let window: DOMWindow | null = null
        do {
            try {
                logger.log("Fetching data from %o", url)
                ;({ window } = await JSDOM.fromURL(url))
            } catch (error: any) {
                if (!error || error.message !== "Error: socket hang up") {
                    throw error
                }
                logger.log(error.message, "then retry.")
                await sleep(2000)
            }
        } while (window == null)

        logger.log("Parsing tables")
        datum.binProperties = await collectValues(
            window,
            binProperties,
            existing.binProperties,
        )
        datum.gcValues = await collectValues(
            window,
            gcValues,
            existing.gcValues,
        )
        datum.scValues = await collectValues(
            window,
            scValues,
            existing.scValues,
        )

        logger.log("Done")
    }

    logger.log("Generating code...")
    let code = `// This file was generated with ECMAScript specifications.
// Do not edit this file directly. Run \`npm run resource-update:unicode-properties\`.
${makeClassDeclarationCode(Object.keys(data))}
export const gcNameSet = new Set(["General_Category", "gc"])
export const scNameSet = new Set(["Script", "Script_Extensions", "sc", "scx"])
export const gcValueSets = new DataSet(${Object.values(data)
        .map((d) => makeDataCode(d.gcValues))
        .join(",")})
export const scValueSets = new DataSet(${Object.values(data)
        .map((d) => makeDataCode(d.scValues))
        .join(",")})
export const binPropertySets = new DataSet(${Object.values(data)
        .map((d) => makeDataCode(d.binProperties))
        .join(",")})
`

    logger.log("Formatting code...")

    const result = await new ESLint({ fix: true }).lintText(code, {
        filePath: FILE_PATH,
    })
    code = result[0].output ?? code

    logger.log("Writing '%s'...", FILE_PATH)
    await writeFile(FILE_PATH, code)

    logger.log("Completed!")
})().catch((error) => {
    logger.error(error.stack)
    process.exitCode = 1
})

async function collectValues(
    window: DOMWindow,
    idSelectorOrProvider: string | (() => AsyncIteratorObject<string>),
    existingSet: Set<string>,
) {
    const getValues =
        typeof idSelectorOrProvider === "function"
            ? idSelectorOrProvider
            : function* () {
                  const selector = `${idSelectorOrProvider} td:nth-child(1) code`
                  const nodes = window.document.querySelectorAll(selector)
                  if (nodes.length === 0) {
                      throw new Error(`No nodes found for selector ${selector}`)
                  }
                  logger.log(
                      "%o nodes of %o were found.",
                      nodes.length,
                      selector,
                  )
                  for (const node of nodes) {
                      yield node.textContent ?? ""
                  }
              }

    const allValues = await Array.fromAsync(getValues())
    const incomingValues = new Set(allValues)
    const allCount = allValues.length

    const missing = existingSet.difference(incomingValues)
    const values = incomingValues.difference(existingSet)

    if (missing.size > 0) {
        throw new Error(`Missing values: ${[...missing].join(", ")}`)
    }

    for (const value of values) {
        existingSet.add(value)
    }

    logger.log(
        "%o adopted and %o ignored as duplication.",
        values.size,
        allCount - values.size,
    )

    return [...values].sort(undefined)
}

function makeClassDeclarationCode(versions: string[]) {
    const rawFields = versions
        .map((v) => `private readonly _raw${v}: string`)
        .join("\n\n")
    const setFields = versions
        .map((v) => `private _set${v}: Set<string> | undefined`)
        .join("\n\n")
    const parameters = versions.map((v) => `raw${v}: string`).join(", ")
    const init = versions.map((v) => `this._raw${v} = raw${v}`).join("\n")
    const getters = versions
        .map(
            (v) =>
                `get es${v}(): Set<string> { return this._set${v} || (this._set${v} = new Set(this._raw${v}.split(" "))) }`,
        )
        .join("\n\n")

    return `
        class DataSet {
            ${rawFields}

            ${setFields}

            // eslint-disable-next-line max-params -- Auto generated
            constructor(${parameters}) {
                ${init}
            }
            ${getters}
        }
    `
}

function makeDataCode(values: string[]) {
    return `"${values
        .map((value) => JSON.stringify(value).slice(1, -1))
        .join(" ")}"`
}
