/**
 * @author Yosuke Ota <https://github.com/ota-meshi>
 * See LICENSE file in root directory for full license.
 */
import * as fs from "node:fs"
import * as path from "node:path"
import { ESLint } from "eslint"
import { getConfigCategories, getConfigCategoriesForAboveConfig } from "./rules"

const Root = path.resolve(__dirname, "../lib/configs/flat")

function wrapCode(code: string, imports = "") {
    return `/**
 * DON'T EDIT THIS FILE.
 * This file was generated by "scripts/update-lib-flat-configs.ts" script.
 */
import type { Linter } from "eslint"
import plugin from "../../index"
${imports ? `${imports}\n` : ""}

const config: Linter.Config = ${code}

export default config
`
}

const configs = getConfigCategories()

for (const filename of fs.globSync("*.js", { cwd: Root })) {
    fs.unlinkSync(path.join(Root, filename))
}

for (const {
    edition,
    rules,
    configName,
    aboveConfigName,
    specKind,
} of configs) {
    if (!configName) {
        continue
    }
    const ruleSetting = rules.map((r) => `"es-x/${r.ruleId}":"error"`).join(",")

    fs.writeFileSync(
        path.join(Root, `${configName}.ts`),
        wrapCode(`{ 
    name: "es-x/${configName}",
    plugins: { get "es-x"() { return plugin } },
    rules: { ${ruleSetting} }
}`),
    )
    if (aboveConfigName) {
        const baseConfigs = getConfigCategoriesForAboveConfig(
            { edition, specKind },
            configs,
        )
        const imports = baseConfigs
            .map(
                (c) =>
                    `import ${getConfigIdentifier(c.configName)} from "./${c.configName}"`,
            )
            .join("\n")
        const extendSetting = baseConfigs
            .map((c) => `...${getConfigIdentifier(c.configName)}.rules`)
            .join(",")
        fs.writeFileSync(
            path.join(Root, `${aboveConfigName}.ts`),
            wrapCode(
                `{
    name: "es-x/${aboveConfigName}",
    plugins: { get "es-x"() { return plugin } },
    rules: {${extendSetting}}
}`,
                imports,
            ),
        )
    }
}

format()

async function format() {
    await ESLint.outputFixes(
        await new ESLint({ fix: true }).lintFiles(["lib/configs/flat"]),
    )
}

function getConfigIdentifier(configName: string) {
    const parts = configName.split(/\W+/u).filter(Boolean)
    return `${parts[0]}${parts
        .slice(1)
        .map((part) => `${part[0].toUpperCase()}${part.slice(1)}`)
        .join("")}Config`
}
