/**
 * @author Toru Nagashima <https://github.com/mysticatea>
 * See LICENSE file in root directory for full license.
 */
import * as fs from "node:fs"
import * as path from "node:path"
import { ESLint } from "eslint"
import { getConfigCategories, getConfigCategoriesForAboveConfig } from "./rules"

const Root = path.resolve(__dirname, "../lib/configs")

function wrapCode(code: string) {
    return `/**
 * DON'T EDIT THIS FILE.
 * This file was generated by "scripts/update-lib-configs.js" script.
 */
"use strict"

module.exports = ${code}
`
}

const configs = getConfigCategories()

for (const {
    edition,
    rules,
    configName,
    aboveConfigName,
    specKind,
} of configs) {
    if (!configName) {
        continue
    }
    const ruleSetting = rules.map((r) => `"es-x/${r.ruleId}":"error"`).join(",")

    fs.writeFileSync(
        path.join(Root, `${configName}.js`),
        wrapCode(`{ plugins: ["es-x"], rules: { ${ruleSetting} } }`),
    )
    if (aboveConfigName) {
        const extendSetting = getConfigCategoriesForAboveConfig(
            { edition, specKind },
            configs,
        )
            .map((c) => `require.resolve("./${c.configName}")`)
            .join(",")
        fs.writeFileSync(
            path.join(Root, `${aboveConfigName}.js`),
            wrapCode(`{ extends: [${extendSetting}] }`),
        )
    }
}

format()

async function format() {
    await ESLint.outputFixes(
        await new ESLint({ fix: true }).lintFiles(["lib/configs"]),
    )
}
