/**
 * DON'T EDIT THIS FILE.
 * This file was generated by "scripts/update-lib-configs.js" script.
 */
"use strict"

module.exports = {
    plugins: ["es-x"],
    rules: {
        "es-x/no-map-prototype-getorinsert": "error",
        "es-x/no-map-prototype-getorinsertcomputed": "error",
        "es-x/no-weakmap-prototype-getorinsert": "error",
        "es-x/no-weakmap-prototype-getorinsertcomputed": "error",
    },
}
